# DESC: Web-стек: nginx/apache, PHP, БД, mkcert (без desktop apps)
PROFILE_DESC="Web-разработка без GUI-приложений"
PROFILE_STEPS="
update_system
install_base_packages
install_zsh
create_directories
install_apache
install_nginx
install_php
configure_php_fpm
configure_xdebug
install_mkcert
install_mariadb
install_postgresql
install_redis
install_memcached
install_composer
install_nvm
create_dev_script
create_new_project_script
create_vhost_script
create_apache_vhost_template
create_nginx_vhost_template
"
