# Apache VirtualHost Template
# Apache использует порты 8080 и 8443 (Nginx на 80 и 443)
#
# Замените SITENAME на имя вашего сайта (например: mysite.test)
# Замените USERNAME на ваше имя пользователя
# Замените ROOTPATH на путь к public директории проекта
# Замените PHPPORT на порт PHP-FPM (8.1→9081 … 8.5→9085)

Define ROOT "ROOTPATH"
Define SITE "SITENAME"

<VirtualHost *:8080>
    DocumentRoot "${ROOT}"
    ServerName ${SITE}
    ServerAlias *.${SITE}
    ErrorLog ${ROOT}/error8080.log
    <Directory "${ROOT}">
        AllowOverride All
        Require all granted
        Options Indexes FollowSymLinks
        <IfModule dir_module>
            DirectoryIndex index.php
        </IfModule>
        <IfModule mpm_itk_module>
            AssignUserId USERNAME USERNAME
        </IfModule>
    </Directory>
    
    <FilesMatch \.php$>
        SetHandler "proxy:fcgi://127.0.0.1:PHPPORT"
    </FilesMatch>
</VirtualHost>

<VirtualHost *:8443>
    DocumentRoot "${ROOT}"
    ServerName ${SITE}
    ServerAlias *.${SITE}
    ErrorLog ${ROOT}/error8443.log
    <Directory "${ROOT}">
        AllowOverride All
        Require all granted
        Options Indexes FollowSymLinks
        <IfModule dir_module>
            DirectoryIndex index.php
        </IfModule>
        <IfModule mpm_itk_module>
            AssignUserId USERNAME USERNAME
        </IfModule>
    </Directory>

    <FilesMatch \.php$>
        SetHandler "proxy:fcgi://127.0.0.1:PHPPORT"
    </FilesMatch>

    SSLEngine on
    SSLCertificateFile      "/etc/ssl/certs/SITENAME.pem"
    SSLCertificateKeyFile   "/etc/ssl/private/SITENAME-key.pem"
</VirtualHost>
